### Shared ###

source ~/.shell/common.sh

### Prompt ###

source ~/.shell/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS=1

if [ -n "$SSH_CLIENT" ]; then
    ssh_flag="(ssh) "
fi

# %B (%b): Start (stop) boldface
# %F (%f): Start (stop) using a different foreground colour, if supported by the terminal
# %n: Username
# %m: Hostname
# %(5~|%-1~/…/%3~|%4~): Prompt dir. trimming
NEWLINE=$'\n'
setopt PROMPT_SUBST ; PS1='%B%F{100}${ssh_flag}%n@%m:%f%F{66}%(5~|%-1~/…/%3~|%4~)%f%b $(__git_ps1 "(%s)")${NEWLINE}\$ '

### ZSH Settings ###

export PATH=~/bin:/usr/local/bin:$PATH
export ZSH=~/.oh-my-zsh

ZSH_DISABLE_COMPFIX="true" # Skip verification of insecure directories (macOS error)
ENABLE_CORRECTION="true"
ZSH_CUSTOM=~/.zsh/custom

plugins=(
    docker                      # Docker completion
    docker-compose
    fzf                         # CTRL+T to search files, CTRL+R to search zsh history
    safe-paste                  # prevent pasted code from running
    wakatime                    # coding metrics
    zsh-autosuggestions         # Autocomplete
    zsh-completions             # Additional completion definitions: https://github.com/zsh-users/zsh-completions/tree/master/src
    zsh-syntax-highlighting     # Fish-shell like syntax highlighting
)

source $ZSH/oh-my-zsh.sh


### Extras ###

source ~/.shell/aws.sh

# Added automatically (and periodically, if missing) on cloud desktop
export AWS_EC2_METADATA_DISABLED=true

