if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zsh/settings.zsh
unalias -a
source ~/.shell/aliases.sh
source ~/.shell/functions.sh
source ~/.shell/common.sh
source ~/.shell/os/"$(uname -s | tr '[:upper:]' '[:lower:]')".sh
source ~/.shell/aws.sh
source ~/.p10k.zsh

autoload -U compinit && compinit
