unalias -a
source ~/.shell/aliases.sh
source ~/.shell/functions.sh
source ~/.shell/common.sh
source ~/.shell/os/"$(uname -s | tr '[:upper:]' '[:lower:]')".sh
source ~/.bash/settings.bash
source ~/.bash/prompt.bash
