source ~/.bash/prompt.bash

unalias -a
source ~/.shell/aliases.sh
source ~/.shell/functions.sh
source ~/.shell/common.sh
source ~/.shell/os/"$(uname | tr '[:upper:]' '[:lower:]')".sh
source ~/.shell/aws.sh

# ZSH default shell on AL2 Cloud Desktop
# Warning: This breaks `bash`
if [[ $(uname -n) == dev-dsk* ]] && [[ -n "$PS1" ]]; then
	# SHELL=/bin/zsh exec /bin/zsh --login
    exec /bin/zsh
fi
